---
title: "Measuring performance"
author: "Joe Shaw"
format: html
---

# Profiling

Profiler: a tool to understand code performance.

Sampling profiler: a profiler which "stops the execution of code every few milliseconds and records the call stack (i.e. which function is currently executing, and the function that called the function, and so on)."

# Packages

**profvis**: profiling visualisation. profvis generates an interactive HTML document where you can examine the performance profile of your code.

**bench**: a package for micro-benchmarking code execution.

# Microbenchmarking

"A **microbenchmark** is a measurement of the performance of a very small piece of code, something that might take milliseconds (ms), microseconds (µs), or nanoseconds (ns) to run."

"Be very wary of generalising the results of microbenchmarks to real code: the observed differences in microbenchmarks will typically be dominated by higher-order effects in real code; *a deep understanding of subatomic physics is not very helpful when baking.*"
