---
title: "Databases"
author: "Joe Shaw"
date: "27/10/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(DBI)
library(dbplyr)
library(tidyverse)
library(duckdb)

```

*"SQL, short for structured query language, is the lingua franca of databases, and is an important language for all data scientists to learn. That said, we’re not going to start with SQL, but instead we’ll teach you dbplyr, which can translate your dplyr code to the SQL."*

*"DBI is a low-level interface that connects to databases and executes SQL"*

*"dbplyr is a high-level interface that translates your dplyr code to SQL queries then executes them with DBI"*

*"At the simplest level, you can think about a database as a collection of data frames, called tables in database terminology. Like a data frame, a database table is a collection of named columns, where every value in the column is the same type. There are three high level differences between data frames and database tables:"*

*"Database tables are stored on disk and can be arbitrarily large. Data frames are stored in memory, and are fundamentally limited (although that limit is still plenty large for many problems)."*

*"Database tables almost always have indexes. Much like the index of a book, a database index makes it possible to quickly find rows of interest without having to look at every single row. Data frames and tibbles don’t have indexes, but data.tables do, which is one of the reasons that they’re so fast."*

*"Most classical databases are optimized for rapidly collecting data, not analyzing existing data. These databases are called row-oriented because the data is stored row-by-row, rather than column-by-column like R. More recently, there’s been much development of column-oriented databases that make analyzing the existing data much faster."*

Client-server database management system: *"run on a powerful central server, which you connect from your computer (the client). They are great for sharing data with multiple people in an organization. Popular client-server DBMS’s include PostgreSQL, MariaDB, **SQL Server**, and Oracle."* 

*"If you can’t find a specific package for your DBMS, you can usually use the odbc package instead. This uses the ODBC protocol supported by many DBMS. odbc requires a little more setup because you’ll also need to install an ODBC driver and tell the odbc package where to find it."*

## Acronyms and Definitions

DSN: data source name

ODBC: open database connectivity (developed by Microsoft in the 1990s)

SQL: structured query language (invented by IBM in the 1970s)

DBMS: database management system

API: application programming interface

CLI: call level interface

ODBC is an API which uses SQL as its database language.

MDE: Microsoft Database Engine file

VBA: Visual BASIC

dbo: the default schema for database tables (“dbo” stands for “database owner”)

Schema: a logical collection of database objects.

You can query the database using SQL or you can use dbplyr to keep using dplyr instead.

## dbplyr

*"dbplyr is a dplyr backend, which means that you keep writing dplyr code but the backend executes it differently."*

*"To use dbplyr, you must first use tbl() to create an object that represents a database table"*

## SQL

*"A query is made up of clauses. There are five important clauses: SELECT, FROM, WHERE, ORDER BY, and GROUP BY."*

dplyr group_by was inspired by SQL GROUP BY. left_join was inspired by LEFT JOIN. case_when was inspired by CASE WHEN.

*"SQL uses NULL instead of NA. NULLs behave similarly to NAs. The main difference is that while they’re “infectious” in comparisons and arithmetic, they are silently dropped when summarizing."*

*"Sometimes it’s not possible to translate a dplyr pipeline into a single SELECT statement and you need to use a subquery. A subquery is just a query used as a data source in the FROM clause, instead of the usual table."*

dbplyr doesn't translate every single dplyr function into SQL, but more and more functions are being added.

*"dbplyr’s translations are certainly not perfect, and there are many R functions that aren’t translated yet, but dbplyr does a surprisingly good job covering the functions that you’ll use most of the time."*

*"The translation of summary functions becomes more complicated when you use them inside a mutate() because they have to turn into so-called window functions."*

I've written up more detailed notes on working with databases in the sql_database_project repo.
