---
title: "Foreword"
format: html
editor: visual
---

# Emergence as the Turing Way's Strategy

"Together, we are trying to change the world. Change research culture, make 
data more accessible, democratise access to knowledge, and ensure that 
artificial intelligence is harnessed for a public, global good. We need 
to dismantle our own biases - sexism, racism, ableism, colonialism, 
capitalism - in order to reach this potential.

We will all fail in this endeavour, every day.

The goal is to get up and try to improve - incrementally - every step we take."

The principle of "emergence": large projects which grow out of individual
contributions. It seems very people-focussed. Rather than forcing a structure or
plan on people, the project grows organically based on people's concerns and
expertise.

# Embracing the principles of Digital Commons

"My commitment to open knowledge and collaboration is deeply rooted in 
my appreciation for Ostrom’s Governing the Commons Ostrom (1990) and 
understanding of the theory and practices of “knowledge commons” as applied 
to digital commons Hess & Ostrom (2006)."

"Knowledge Commons: Knowledge Commons refers to collectively owned and 
managed knowledge, like data, content, and software. Unlike physical 
resources, this knowledge, once shared, can be used by countless people 
simultaneously without any depletion."

"The Turing Way is also aligned with the principles of Digital Public Goods 
(DPG) -- digital assets that provide value to society and contribute to 
the public good."
